---
- name: Check Apache conf
  block:

    - name: Check loaded conf
      block:

        - name: Register the loaded conf
          command: a2query -c
          check_mode: false
          changed_when: false
          register: apache_conf_check

      rescue:

        - name: No conf enabled
          set_fact:
            apache_conf_loaded: []
          when: '"No conf matches" in apache_conf_check.stderr'

    - name: Set an array of loaded Apache conf
      block:

        - name: Debug the loaded conf
          debug:
            var: apache_conf_check.stdout_lines
            verbosity: 2

        - name: Set apache_conf_loaded to an empty array
          set_fact:
            apache_conf_loaded: []

        - name: Set an array of the loaded conf
          set_fact:
            apache_conf_loaded: "{{ apache_conf_loaded | default([]) + [ line.split(' ')[0] ] }}"
          loop: "{{ apache_conf_check.stdout_lines }}"
          loop_control:
            loop_var: line
            label: "{{ line }}"

      when:
        - apache_conf_check.stdout is defined
        - apache_conf_check.stderr | length == 0

    - name: Debug loaded conf
      debug:
        var: apache_conf_loaded
        verbosity: 1

  tags:
    - apache
...
