# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Disable and enable Apache conf
  block:

    - name: Apache conf disabled
      ansible.builtin.command: "a2disconf {{ apache_conf }}"
      args:
        removes: "/etc/apache2/conf-enabled/{{ apache_conf }}.conf"
      when:
        - apache_conf_disabled is defined
        - apache_conf_disabled != []
        - apache_conf in ansible_local.a2query.conf_enabled
      loop: "{{ apache_conf_disabled }}"
      loop_control:
        loop_var: apache_conf
        label: "{{ apache_conf }}"
      notify: Restart Apache

    - name: Check that all the conf to be enabled exist
      ansible.builtin.stat:
        path: "/etc/apache2/conf-available/{{ apache_conf }}.conf"
      when: apache_conf not in ansible_local.a2query.conf_enabled
      register: apache_conf_path
      failed_when:
        - not ansible_check_mode | bool
        - not apache_conf_path.stat.exists | bool
      loop: "{{ apache_conf_enabled }}"
      loop_control:
        loop_var: apache_conf
        label: "{{ apache_conf }}"

    - name: Apache conf enabled
      ansible.builtin.command: "a2enconf {{ apache_conf }}"
      args:
        creates: "/etc/apache2/conf-enabled/{{ apache_conf }}.conf"
      when:
        - apache_conf_enabled is defined
        - apache_conf_enabled != []
        - apache_conf not in ansible_local.a2query.conf_enabled
      loop: "{{ apache_conf_enabled }}"
      loop_control:
        loop_var: apache_conf
        label: "{{ apache_conf }}"
      notify: Restart Apache

  tags:
    - apache
...
