# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Disable and enable Apache conf
  block:

    - name: Check loaded conf
      ansible.builtin.include_tasks: a2conf_checks.yml

    - name: Apache conf disabled
      ansible.builtin.command: "a2disconf {{ conf }}"
      args:
        removes: "/etc/apache2/conf-enabled/{{ conf }}.conf"
      when:
        - apache_conf_disabled is defined
        - apache_conf_disabled != []
        - conf in apache_conf_loaded
      loop: "{{ apache_conf_disabled }}"
      loop_control:
        loop_var: conf
        label: "{{ conf }}"

    - name: Apache conf enabled
      ansible.builtin.command: "a2enconf {{ conf }}"
      args:
        creates: "/etc/apache2/conf-enabled/{{ conf }}.conf"
      when:
        - apache_conf_enabled is defined
        - apache_conf_enabled != []
        - conf not in apache_conf_loaded
      loop: "{{ apache_conf_enabled }}"
      loop_control:
        loop_var: conf
        label: "{{ conf }}"

  tags:
    - apache
...
