---
- name: Disable and enable Apache conf
  block:

    - name: Check loaded conf
      block:

        - name: Register the loaded conf
          command: a2query -c
          check_mode: false
          changed_when: false
          register: apache_conf_check

      rescue:

        - name: No conf enabled
          set_fact:
            apache_conf_loaded: []
          when: '"No conf matches" in apache_conf_check.stderr'

    - name: Debug the loaded conf
      debug:
        var: apache_conf_check.stdout_lines
        verbosity: 2
      when: apache_conf_check.stdout is defined

    - name: Set an array of the loaded conf
      set_fact:
        apache_conf_loaded: "{{ apache_conf_loaded | default([]) + [ line.split(' ')[0] ] }}"
      when: apache_conf_check.stdout is defined
      loop: "{{ apache_conf_check.stdout_lines }}"
      loop_control:
        loop_var: line
        label: "{{ line }}"

    - name: Debug loaded conf
      debug:
        var: apache_conf_loaded
        verbosity: 2

    - name: Apache conf disabled
      command: "a2disconf {{ conf }}"
      args:
        removes: "/etc/apache2/conf-enabled/{{ conf }}.conf"
      when:
        - apache_conf_disabled is defined
        - apache_conf_disabled != []
        - conf in apache_conf_loaded
      loop: "{{ apache_conf_disabled }}"
      loop_control:
        loop_var: conf
        label: "{{ conf }}"

    - name: Apache conf enabled
      command: "a2enconf {{ conf }}"
      args:
        creates: "/etc/apache2/conf-enabled/{{ conf }}.conf"
      when:
        - apache_conf_enabled is defined
        - apache_conf_enabled != []
        - conf not in apache_conf_loaded
      loop: "{{ apache_conf_enabled }}"
      loop_control:
        loop_var: conf
        label: "{{ conf }}"

  tags:
    - apache
...
