---
- name: "Apache {{ mod }} module checked"
  stat:
    path: "/etc/apache2/mods-enabled/{{ mod }}.conf"
  register: apache_mod_status
  tags:
    - apache

- name: "Apache {{ mod }} module config disabled"
  apache2_module:
    name: "{{ mod }}"
    state: absent
  register: apache_a2enmod
  when: apache_mod_status.stat.exists
  tags:
    - apache
...
