---
- name: "Apache {{ mod }} module checked"
  stat:
    path: "/etc/apache2/mods-enabled/{{ mod }}.conf"
  register: apache_mod_status
  tags:
    - apache

- name: "Disable Apache {{ mod }} module"
  block:

    - name: "Apache {{ mod }} module config checked and disabled"
      apache2_module:
        name: "{{ mod }}"
        identifier: "{{ mod }}_module"
        state: absent
        ignore_configcheck: false
      register: apache_a2enmod
      when: mod is not regex("^mpm_[event|itk|prefork]$")

    - name: "Apache {{ mod }} module disabled without config checked"
      apache2_module:
        name: "{{ mod }}"
        identifier: "{{ mod }}_module"
        state: absent
        ignore_configcheck: true
      register: apache_a2enmod
      when: mod is regex("^mpm_[event|itk|prefork]$")

  when: apache_mod_status.stat.exists
  tags:
    - apache
...
