---
- name: "Apache {{ mod }} module checked"
  stat:
    path: "/etc/apache2/mods-enabled/{{ mod }}.conf"
  register: apache_mod_status
  tags:
    - apache

- name: "Enable Apache {{ mod }} module"
  block:

    - name: "Apache {{ mod }} module enabled"
      apache2_module:
        name: "{{ mod }}"
        state: present
      register: apache_a2enmod
      when: apache_mod_status.stat.exists == False

  rescue:

    - name: Debug error
      debug:
        var: apache_a2enmod
        verbosity: 1
      when: apache_a2enmod is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.rc: {{ apache_a2enmod.rc }}"
        verbosity: 1
      when: apache_a2enmod.rc is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.result: {{ apache_a2enmod.result }}"
        verbosity: 1
      when: apache_a2enmod.result is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.stderr: {{ apache_a2enmod.stderr }}"
        verbosity: 1
      when: apache_a2enmod.stderr is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.stdout: {{ apache_a2enmod.stdout }}"
        verbosity: 1
      when: apache_a2enmod.stdout is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.warnings: {{ apache_a2enmod.warnings }}"
        verbosity: 1
      when: apache_a2enmod.warnings is defined

    - name: Debug error
      debug:
        msg:
          - "apache_a2enmod.rc: {{ apache_a2enmod.rc }}"
          - "apache_a2enmod.result: {{ apache_a2enmod.result }}"
          - "apache_a2enmod.stderr: {{ apache_a2enmod.stderr }}"
          - "apache_a2enmod.stdout: {{ apache_a2enmod.stdout }}"
          - "apache_a2enmod.warnings: {{ apache_a2enmod.warnings }}"
        verbosity: 1
      when: apache_a2enmod.rc is defined

    - name: "Enable Apache mpm_event"
      apache2_module:
        name: mpm_event
        state: present
        ignore_configcheck: true
      when:
        - ( "Configuration error: No MPM loaded" in apache_a2enmod.stderr )
        - mod == "mpm_event"

    - name: "Disable php{{ apache_php_version }} and mpm_prefork and then enable mpm_event"
      block:

        - name: "Disable Apache module php{{ apache_php_version }}"
          apache2_module:
            name: "php{{ apache_php_version }}"
            state: absent

        - name: "Disable Apache module mpm_prefork"
          apache2_module:
            name: mpm_prefork
            state: absent

        - name: "Enable Apache mpm_event"
          apache2_module:
            name: mpm_event
            state: present

      when: ( "Considering conflict mpm_worker for mpm_event" or "Considering conflict mpm_prefork for mpm_event" in apache_a2enmod.stdout )

  tags:
    - apache
...
