---
- name: "Apache {{ mod }} module checked"
  stat:
    path: "/etc/apache2/mods-enabled/{{ mod }}.conf"
  register: apache_mod_status
  tags:
    - apache

- name: "Enable Apache {{ mod }} module"
  block:

    - name: "Apache {{ mod }} module enabled"
      apache2_module:
        name: "{{ mod }}"
        state: present
      register: apache_a2enmod
      when: apache_mod_status.stat.exists == False

  rescue:

    - name: "Disable mod_php and then enable mpm_event"
      block:

        - name:
          apache2_module:
            name: "php{{ apache_php_version }}"
            state: absent

        - name:
          apache2_module:
            name: mpm_prefork
            state: absent

      when: ( "Considering conflict mpm_worker for mpm_event" or "Considering conflict mpm_prefork for mpm_event" in apache_a2enmod.stdout )

  tags:
    - apache
...
