---
- name: Apache module checks
  block:

    - name: Check loaded modules
      block:

        - name: Register the loaded modules
          command: a2query -m
          check_mode: false
          changed_when: false
          register: apache_modules_check

      rescue:

        - name: No mod enabled
          set_fact:
            apache_modules_loaded: []
          when: ( "No module matches" in apache_modules_check.stderr )

    - name: Set an array of loaded Apache modules
      block:

        - name: Debug the loaded modules
          debug:
            var: apache_modules_check.stdout_lines
            verbosity: 2

        - name: Set apache_modules_loaded to an ampty array
          set_fact:
            apache_modules_loaded: []

        - name: Set an array of the loaded modules
          set_fact:
            apache_modules_loaded: "{{ apache_modules_loaded + [ line.split(' ')[0] ] }}"
          loop: "{{ apache_modules_check.stdout_lines }}"
          loop_control:
            loop_var: line
            label: "{{ line }}"

      when:
        - apache_modules_check.stdout is defined
        - apache_modules_check.stderr is not defined

    - name: Debug loaded modules
      debug:
        var: apache_modules_loaded
        verbosity: 1

  tags:
    - apache
...
