# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Check loaded modules
  ansible.builtin.include_tasks: a2mod_checks.yml
  tags:
    - apache

- name: Apache modules disabled
  block:

    - name: Apache ITK MPM package absent
      ansible.builtin.apt:
        pkg:
          - libapache2-mpm-itk
        state: absent
        update_cache: false
      when: '"mpm_itk" in apache_mods_disabled'

    - name: Apache FastCGI absent
      ansible.builtin.apt:
        pkg:
          - libapache2-mod-fcgid
        state: absent
        update_cache: false
      when: '"fcgid" in apache_mods_disabled'

    - name: Apache suEXEC package absent
      ansible.builtin.apt:
        pkg:
          - apache2-suexec-pristine
        state: absent
        update_cache: false
      when: '"suexec" in apache_mods_disabled'

    - name: "Apache package absent {{ apache_phpfpm_mod }}"
      ansible.builtin.apt:
        pkg:
          - "libapache2-mod-php{{ apache_php_version }}"
        state: absent
        update_cache: false
      when: ( apache_php ) and ( "apache_phpfpm_mod" in apache_mods_disabled )

    - name: Disable modules
      community.general.apache2_module:
        name: "{{ mod }}"
        state: absent
      when: mod in apache_modules_loaded
      loop: "{{ apache_mods_disabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  when:
    - apache_mods_disabled is defined
    - apache_mods_disabled != []
  tags:
    - apache

- name: Apache modules enabled
  block:

    - name: Apache ITK MPM package present
      ansible.builtin.apt:
        pkg:
          - libapache2-mpm-itk
        state: present
        update_cache: false
      when: '"mpm_itk" in apache_mods_enabled'

    - name: Apache Suexec package present
      ansible.builtin.apt:
        pkg:
          - apache2-suexec-pristine
        state: present
        update_cache: false
      when: '"suexec" in apache_mods_enabled'

    - name: Apache FastCGI package present
      ansible.builtin.apt:
        pkg:
          - libapache2-mod-fcgid
        state: present
        update_cache: false
      when: '"fcgid" in apache_mods_enabled'

    - name: Apache mod_php package present
      ansible.builtin.apt:
        pkg:
          - "libapache2-mod-php{{ apache_php_version }}"
        state: present
        update_cache: false
      when: ( apache_php ) and ( "apache_phpfpm_mod" in apache_mods_enabled )

    - name: Apache modules enabled
      community.general.apache2_module:
        name: "{{ mod }}"
        state: present
      when: mod not in apache_modules_loaded
      loop: "{{ apache_mods_enabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  when:
    - apache_mods_enabled is defined
    - apache_mods_enabled != []
  tags:
    - apache
...
