---
- name: Apache module checks
  block:

    - name: Check loaded modules
      block:

        - name: Register the loaded modules
          command: a2query -m
          check_mode: false
          changed_when: false
          register: apache_modules_check

      rescue:

        - name: No mod enabled
          set_fact:
            apache_modules_loaded: []
          when: ( "No module matches" in apache_modules_check.stderr )

    - name: Debug the loaded modules
      debug:
        var: apache_modules_check.stdout_lines
        verbosity: 2
      when: apache_modules_check.stdout is defined

    - name: Set an array of the loaded modules
      set_fact:
        apache_modules_loaded: "{{ apache_modules_loaded | default([]) + [ line.split(' ')[0] ] }}"
      when: apache_modules_check.stdout is defined
      loop: "{{ apache_modules_check.stdout_lines }}"
      loop_control:
        loop_var: line
        label: "{{ line }}"

    - name: Debug loaded modules
      debug:
        var: apache_modules_loaded
        verbosity: 2
      when: apache_modules_loaded is defined

  tags:
    - apache

- name: Apache modules disabled
  block:

    - name: Apache ITK MPM package absent
      apt:
        pkg:
          - libapache2-mpm-itk
        state: absent
        update_cache: false
      when: '"mpm_itk" in apache_mods_disabled'

    - name: Apache FastCGI absent
      apt:
        pkg:
          - libapache2-mod-fcgid
        state: absent
        update_cache: false
      when: '"fcgid" in apache_mods_disabled'

    - name: Apache suEXEC package absent
      apt:
        pkg:
          - apache2-suexec-pristine
        state: absent
        update_cache: false
      when: '"suexec" in apache_mods_disabled'

    - name: "Apache {{ apache_phpfpm_mod }} package absent"
      apt:
        pkg:
          - "libapache2-mod-php{{ apache_php_version }}"
        state: absent
        update_cache: false
      when: ( apache_php ) and ( "apache_phpfpm_mod" in apache_mods_disabled )

    - name: Disable modules
      apache2_module:
        name: "{{ mod }}"
        state: absent
      when: mod in apache_modules_loaded
      loop: "{{ apache_mods_disabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  when:
    - apache_mods_disabled is defined
    - apache_mods_disabled != []
  tags:
    - apache

- name: Apache modules enabled
  block:

    - name: Apache ITK MPM package present
      apt:
        pkg:
          - libapache2-mpm-itk
        state: present
        update_cache: false
      when: '"mpm_itk" in apache_mods_enabled'

    - name: Apache Suexec package present
      apt:
        pkg:
          - apache2-suexec-pristine
        state: present
        update_cache: false
      when: '"suexec" in apache_mods_enabled'

    - name: Apache FastCGI package present
      apt:
        pkg:
          - libapache2-mod-fcgid
        state: present
        update_cache: false
      when: '"fcgid" in apache_mods_enabled'

    - name: Apache mod_php package present
      apt:
        pkg:
          - "libapache2-mod-php{{ apache_php_version }}"
        state: present
        update_cache: false
      when: ( apache_php ) and ( "apache_phpfpm_mod" in apache_mods_enabled )

    - name: Apache modules enabled
      apache2_module:
        name: "{{ mod }}"
        state: present
      when: mod not in apache_modules_loaded
      loop: "{{ apache_mods_enabled }}"
      loop_control:
        loop_var: mod
        label: "{{ mod }}"

  when:
    - apache_mods_enabled is defined
    - apache_mods_enabled != []
  tags:
    - apache
...
