# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apache module checks
  block:

    - name: Check loaded modules
      block:

        - name: Register the loaded modules
          ansible.builtin.command: a2query -m
          check_mode: false
          changed_when: false
          register: apache_modules_check

      rescue:

        - name: No mod enabled
          ansible.builtin.set_fact:
            apache_modules_loaded: []
          when: ( "No module matches" in apache_modules_check.stderr )

    - name: Set an array of loaded Apache modules
      block:

        - name: Debug the loaded modules
          ansible.builtin.debug:
            var: apache_modules_check.stdout_lines
            verbosity: 2

        - name: Set apache_modules_loaded to an empty array
          ansible.builtin.set_fact:
            apache_modules_loaded: []

        - name: Set an array of the loaded modules
          ansible.builtin.set_fact:
            apache_modules_loaded: "{{ apache_modules_loaded + [line.split(' ')[0]] }}"
          loop: "{{ apache_modules_check.stdout_lines }}"
          loop_control:
            loop_var: line
            label: "{{ line }}"

      when:
        - apache_modules_check.stdout is defined
        - apache_modules_check.stderr | length == 0

    - name: Debug loaded modules
      ansible.builtin.debug:
        var: apache_modules_loaded
        verbosity: 1

  tags:
    - apache
...
