# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Fact set for apt version
  block:

    - name: Get the apt package facts
      ansible.builtin.package_facts:
        manager: apt
      when: ansible_facts.packages is not defined

    - name: Set a fact for the apt package version
      ansible.builtin.set_fact:
        apache_apt_version: "{{ ansible_facts.packages.apt[0].version }}"

    - name: Debug apache_apt_version
      ansible.builtin.debug:
        var: apache_apt_version
      tags:
        - debug

    - name: Check that apache_apt_version is a semver >= 2.0.0
      ansible.builtin.assert:
        that:
          - apache_apt_version is ansible.builtin.version('2.0.0', 'gt', version_type='semver')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

  tags:
    - apache
    - apache_apt

- name: Apache Sury repo enabled
  block:

    - name: Linux distro check for Sury Apache apt repo
      ansible.builtin.assert:
        that:
          - ansible_facts.distribution_release in apache_sury_distros
        fail_msg: >-
          The packages.sury.org Apache repo only supports {{ apache_sury_distros | ansible.builtin.join(', ') }}, not {{ ansible_facts.distribution_release }}.

    - name: Required apt packages present
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - lsb-release
          - python3-debian
        state: present

    - name: Package debsuryorg-archive-keyring.deb present
      ansible.builtin.apt:
        deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
        state: present

    - name: Stat /usr/share/keyrings/debsuryorg-archive-keyring.gpg
      ansible.builtin.stat:
        path: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
      register: apache_apt_key_path

    - name: The GPG key provided by the debsuryorg-archive-keyring.deb package is required
      ansible.builtin.assert:
        that:
          - apache_apt_key_path.stat.exists | ansible.builtin.bool
        quiet: "{% if ansible_check_mode or ansible_verbosity >= 1 %}false{% else %}true{% endif %}"
        fail_msg: >-
          The GPG key provided by https://packages.sury.org/debsuryorg-archive-keyring.deb is required to configure the Sury PHP repo.
          It should be present at /usr/share/keyrings/debsuryorg-archive-keyring.gpg

    - name: Configure the Sury apt repo when the GPG public key is present
      block:

        - name: Stat Apache repository sources file
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/apache.sources
          register: apache_sources_path

        - name: Read and backup Apache repository sources file
          block:

            - name: Read the Apache repository sources file
              ansible.builtin.include_tasks: sources_file.yml

            - name: Set a fact for the prior Apache repository sources file contents
              ansible.builtin.set_fact:
                apache_sources_contents_prior: "{{ apache_sources_contents }}"
              when: apache_sources_contents is defined

            - name: Include check Apache repository sources file present for ansible < 2.21.0 and / or apt < 3.1.0
              ansible.builtin.include_tasks:
                file: deb822_check_legacy.yml
              when: >-
                (apache_apt_version is ansible.builtin.version('3.1.0', '<')) or
                (ansible_version.full is ansible.builtin.version('2.21.0', '<'))

            - name: Check Apache repository sources file present for ansible >= 2.21.0 and apt >= 3.1.0
              ansible.builtin.include_tasks:
                file: deb822_check.yml
              when:
                - ansible_version.full is ansible.builtin.version('2.21.0', '>=')
                - apache_apt_version is ansible.builtin.version('3.1.0', '>=')

            - name: Debug apache_sources_check
              ansible.builtin.debug:
                var: apache_sources_check
                # verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
              when:
                - apache_sources_check is defined
              tags:
                - debug

            - name: Backup old apache.sources file
              ansible.builtin.command:
                cmd: >-
                  mv
                  /etc/apt/sources.list.d/apache.sources
                  /etc/apt/sources.list.d/.apache.sources.{{ apache_date_timestamp }}.ansible.save
              args:
                creates: "/etc/apt/sources.list.d/.apache.sources.{{ apache_date_timestamp }}.ansible.save"
                removes: /etc/apt/sources.list.d/apache.sources
              vars:
                apache_date_timestamp: "{{ ansible_facts.date_time.iso8601_basic_short }}"
              when:
                - apache_sources_check is defined
                - apache_sources_check.repo is defined
                - apache_sources_contents_prior != apache_sources_check.repo | string | community.general.jc('ini')

          when: apache_sources_path.stat.exists | ansible.builtin.bool

        - name: Include Apache repository sources file present for apt < 3.1.0
          ansible.builtin.include_tasks:
            file: deb822_legacy.yml
          when: apache_apt_version is ansible.builtin.version('3.1.0', '<')

        - name: Include Apache repository sources file present for apt >= 3.1.0
          ansible.builtin.include_tasks:
            file: deb822_legacy.yml
          when: apache_apt_version is ansible.builtin.version('3.1.0', '>=')

        - name: Print the changes in the Apache repository sources file  # noqa: no-handler
          block:

            - name: Debug updated apache_sources.repo
              ansible.builtin.debug:
                var: apache_sources.repo
                verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
              tags:
                - debug

            - name: Diff Apache repository sources file update
              ansible.utils.fact_diff:
                before: "{{ apache_sources_contents_prior | ansible.builtin.to_nice_yaml }}"
                after: "{{ apache_sources.repo | string | community.general.jc('ini') | ansible.builtin.to_nice_yaml }}"
              when:
                - (ansible_check_mode | ansible.builtin.bool) or (ansible_diff_mode | ansible.builtin.bool)
                - apache_sources_contents_prior is defined
                - apache_sources.repo is defined

          when: apache_sources.changed | ansible.builtin.bool

        - name: Apache apt preferences present
          ansible.builtin.template:
            src: apache.pref.j2
            dest: /etc/apt/preferences.d/apache.pref
            mode: "0644"
            owner: root
            group: root
          register: apache_preferences

        - name: Update apt cache and autoclean and autoremove
          block:

            - name: Update apt cache  # noqa: no-handler
              ansible.builtin.apt:
                update_cache: true
                cache_valid_time: 0
              check_mode: false
              changed_when: false

            - name: Apt autoclean and autoremove  # noqa: no-handler
              ansible.builtin.apt:
                upgrade: dist
                autoclean: true
                autoremove: true
                update_cache: false

          when: >-
            (apache_sources.changed | ansible.builtin.bool) or
            (apache_preferences.changed | ansible.builtin.bool)
          tags:
            - molecule-idempotence-notest

      when: apache_apt_key_path.stat.exists | ansible.builtin.bool

  when: apache_sury | ansible.builtin.bool

  tags:
    - apache
    - apache_apt

- name: Sury Apache apt repo absent
  block:

    - name: Include file absent tasks
      ansible.builtin.include_tasks: file_absent.yml
      loop:
        - /etc/apt/sources.list.d/apache.sources
        - /etc/apt/preferences.d/apache.pref
      loop_control:
        loop_var: apache_file_absent
        label: "{{ apache_file_absent | ansible.builtin.basename }}"

    - name: Update apt cache  # noqa: no-handler
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      tags:
        - molecule-idempotence-notest

    - name: Apt autoclean and autoremove  # noqa: no-handler
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: false
      tags:
        - molecule-idempotence-notest

  when: not apache_sury | ansible.builtin.bool
  tags:
    - apache
    - apache_apt

- name: Apache apt package tasks
  block:

    - name: Debug apache_pkg_absent
      ansible.builtin.debug:
        var: apache_pkg_absent
        verbosity: "{% if (ansible_check_mode | ansible.builtin.bool) or (ansible_diff_mode | ansible.builtin.bool) %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Debug apache_pkg_absent | ansible.builtin.type_debug
      ansible.builtin.debug:
        msg: "{{ apache_pkg_absent | ansible.builtin.type_debug }}"
        verbosity: "{% if (ansible_check_mode | ansible.builtin.bool) or (ansible_diff_mode | ansible.builtin.bool) %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Debug apache_pkg_present
      ansible.builtin.debug:
        var: apache_pkg_present
        verbosity: "{% if (ansible_check_mode | ansible.builtin.bool) or (ansible_diff_mode | ansible.builtin.bool) %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Debug apache_pkg_present | ansible.builtin.type_debug
      ansible.builtin.debug:
        msg: "{{ apache_pkg_present | ansible.builtin.type_debug }}"
        verbosity: "{% if (ansible_check_mode | ansible.builtin.bool) or (ansible_diff_mode | ansible.builtin.bool) %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Debug Apache packages to be removed
      ansible.builtin.debug:
        msg: "The following packages are due to be removed: {{ apache_pkg_absent | ansible.builtin.join(', ') }}"

    - name: Apache packages absent
      ansible.builtin.apt:
        pkg: "{{ apache_pkg_absent }}"
        state: absent
        update_cache: true
        cache_valid_time: 60
      when:
        - apache_pkg_absent != []
        - apache_pkg_absent | ansible.builtin.type_debug != none
      notify: Restart Apache

    - name: Debug Apache packages to be installed
      ansible.builtin.debug:
        msg: "The following packages are due to be installed: {{ apache_pkg_present | ansible.builtin.join(', ') }}"

    - name: Apache packages present
      ansible.builtin.apt:
        pkg: "{{ apache_pkg_present }}"
        state: present
        install_recommends: true
        update_cache: true
        cache_valid_time: 60
      when:
        - apache_pkg_present != []
        - apache_pkg_present | ansible.builtin.type_debug != none
      notify: Restart Apache

  tags:
    - apache
    - apache_install
    - apache_local_facts
...
