# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Debug tasks required
  block:

    - name: Sury Apache apt repo is required for packages present
      ansible.builtin.debug:
        var: apache_sury_pkg_present
      when: apache_sury_pkg_present != []

    - name: Sury Apache apt repo is required for packages absent
      ansible.builtin.debug:
        var: apache_sury_pkg_absent
      when: apache_sury_pkg_absent != []

    - name: Sury Apache apt repo is not required
      ansible.builtin.debug:
        msg: No Sury Apache apt packages are to be installed or removed
      when:
        - apache_sury_pkg_absent == []
        - apache_sury_pkg_present == []

  tags:
    - apache
    - apache_apt
    - debug

# TODO Remove Sury packages present when none are to be installed

- name: Sury Apache apt repo present
  block:

    - name: Python3 Debian present for deb822 module
      ansible.builtin.apt:
        pkg: python3-debian
        state: present

    - name: Package debsuryorg-archive-keyring.deb present
      ansible.builtin.apt:
        deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
        state: present

    - name: Stat /usr/share/keyrings/debsuryorg-archive-keyring.gpg
      ansible.builtin.stat:
        path: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
      register: apache_apt_key_path

    - name: The GPG key provided by the debsuryorg-archive-keyring.deb package is required
      ansible.builtin.assert:
        that:
          - apache_apt_key_path.stat.exists | bool
        quiet: "{% if ansible_check_mode or ansible_verbosity >= 1 %}false{% else %}true{% endif %}"
        fail_msg: >-
          The GPG key provided by https://packages.sury.org/debsuryorg-archive-keyring.deb is required to configure the Sury PHP repo.
          It should be present at /usr/share/keyrings/debsuryorg-archive-keyring.gpg

    - name: Configure the Sury apt repo when the GPG public key is present
      block:

        - name: Stat Apache repository sources file
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/apache.sources
          register: apache_sources_path

        - name: Read and backup Apache repository sources file
          block:

            - name: Read the Apache repository sources file
              ansible.builtin.include_tasks: sources_file.yml

            - name: Set a fact for the prior Apache repository sources file contents
              ansible.builtin.set_fact:
                apache_sources_contents_prior: "{{ apache_sources_contents }}"
              when: apache_sources_contents is defined

            - name: Check Apache repository sources file present
              ansible.builtin.deb822_repository:
                allow_downgrade_to_insecure: false
                allow_insecure: false
                allow_weak: false
                architectures: "{{ ansible_facts.ansible_local.dpkg.arch }}"
                check_date: true
                check_valid_until: true
                components: main
                enabled: true
                name: apache
                pdiffs: true
                signed_by: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
                suites: "{{ ansible_facts.distribution_release }}"
                types: deb
                uris: https://packages.sury.org/apache/
              check_mode: true
              changed_when: false
              register: apache_sources_check

            - name: Debug proposed apache_sources_check.repo
              ansible.builtin.debug:
                var: apache_sources_check.repo
                verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"
              tags:
                - debug

            - name: Backup old apache.sources file
              ansible.builtin.command:
                cmd: >-
                  mv
                  /etc/apt/sources.list.d/apache.sources
                  /etc/apt/sources.list.d/.apache.sources.{{ apache_date_timestamp }}.ansible.save
              args:
                creates: "/etc/apt/sources.list.d/.apache.sources.{{ apache_date_timestamp }}.ansible.save"
                removes: /etc/apt/sources.list.d/apache.sources
              vars:
                apache_date_timestamp: "{{ ansible_facts.date_time.iso8601_basic_short }}"
              when: apache_sources_contents_prior != apache_sources_check.repo | string | community.general.jc('ini')

          when: apache_sources_path.stat.exists | bool

        - name: Apache repository sources file present
          ansible.builtin.deb822_repository:
            allow_downgrade_to_insecure: false
            allow_insecure: false
            allow_weak: false
            architectures: "{{ ansible_facts.ansible_local.dpkg.arch }}"
            check_date: true
            check_valid_until: true
            components: main
            enabled: true
            name: apache
            pdiffs: true
            signed_by: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
            suites: "{{ ansible_facts.distribution_release }}"
            types: deb
            uris: https://packages.sury.org/apache/
          register: apache_sources

        - name: Print the changes in the Apache repository sources file  # noqa: no-handler
          block:

            - name: Debug updated apache_sources.repo
              ansible.builtin.debug:
                var: apache_sources.repo
                verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"
              tags:
                - debug

            - name: Diff Apache repository sources file update
              ansible.utils.fact_diff:
                before: "{{ apache_sources_contents_prior | ansible.builtin.to_nice_yaml }}"
                after: "{{ apache_sources.repo | string | community.general.jc('ini') | ansible.builtin.to_nice_yaml }}"
              when:
                - (ansible_check_mode | bool) or (ansible_diff_mode | bool)
                - apache_sources_contents_prior is defined
                - apache_sources.repo is defined

          when: apache_sources.changed | bool

        - name: Apache apt preferences present
          ansible.builtin.template:
            src: apache.pref.j2
            dest: /etc/apt/preferences.d/apache.pref
            mode: "0644"
            owner: root
            group: root
          register: apache_preferences

        - name: Update apt cache and autoclean and autoremove
          block:

            - name: Update apt cache  # noqa: no-handler
              ansible.builtin.apt:
                update_cache: true
                cache_valid_time: 0
              check_mode: false
              changed_when: false

            - name: Apt autoclean and autoremove  # noqa: no-handler
              ansible.builtin.apt:
                upgrade: dist
                autoclean: true
                autoremove: true
                update_cache: false

          when: >-
            (apache_sources.changed | bool) or
            (apache_preferences.changed | bool)
          tags:
            - molecule-idempotence-notest

      when: apache_apt_key_path.stat.exists | bool

  when: (apache_sury_pkg_absent != []) or (apache_sury_pkg_present != [])

  tags:
    - apache
    - apache_apt

- name: Sury Apache apt repo absent
  block:

    - name: Include file absent tasks
      ansible.builtin.include_tasks: file_absent.yml
      loop:
        - /etc/apt/sources.list.d/apache.sources
        - /etc/apt/preferences.d/apache.pref
      loop_control:
        loop_var: apache_file_absent
        label: "{{ apache_file_absent | ansible.builtin.basename }}"

    - name: Update apt cache  # noqa: no-handler
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      tags:
        - molecule-idempotence-notest

    - name: Apt autoclean and autoremove  # noqa: no-handler
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: false
      tags:
        - molecule-idempotence-notest

  when:
    - apache_sury_pkg_absent == []
    - apache_sury_pkg_present == []
  tags:
    - apache
    - apache_apt
