---
- name: Download Cloudflare IPv4 list
  get_url:
    url: "https://www.cloudflare.com/ips-v4"
    dest: "/root/cloudflare_ips_v4.txt"
  tags:
    - apache

- name: Slurp Cloudflare IPv4 list
  slurp:
    src: "/root/cloudflare_ips_v4.txt"
  register: "apache_cloudflare_ips_v4_b64encoded"
  tags:
    - apache

- name: Create an array from the Cloudflare IP lists
  set_fact:
    apache_cloudflare_ips: "{{ apache_cloudflare_ips_v4_b64encoded['content'] | b64decode | regex_replace('\n', '|').split('|') }}"
  tags:
    - apache

- name: Debug Cloudflare IP array
  debug:
    msg: "apache_cloudflare_ips: {{ apache_cloudflare_ips }}"
    verbosity: 1
  tags:
    - apache

- fail:
    msg: Debug
  tags:
    - apache
...
