# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apache local facts
  block:

    - name: Ansible facts.d directory present
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Ansible a2query local facts script absent
      ansible.builtin.file:
        path: /etc/ansible/facts.d/a2query.fact
        state: absent

    - name: Ansible apache local facts script present
      ansible.builtin.template:
        src: apache.fact.j2
        dest: /etc/ansible/facts.d/apache.fact
        mode: "0755"
        owner: root
        group: root
        validate: bash %s

    - name: Stat /etc/ansible/facts.d/apache.fact
      ansible.builtin.stat:
        path: /etc/ansible/facts.d/apache.fact
      register: apache_facts_script

    - name: Read and debug apache local facts
      block:

        - name: Read apache local facts  # noqa: no-handler
          ansible.builtin.setup:
            filter: ansible_local
          check_mode: false
          changed_when: false
          register: apache_facts

        - name: Debug apache_facts
          ansible.builtin.debug:
            var: apache_facts
            verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}0{% else %}1{% endif %}"
          tags:
            - debig

      when: apache_facts_script.stat.exists

  tags:
    - apache
    - apache_local_facts
    - apache_install
...
