---
- name: Config for mc3.coop
  block:

    - name: mc3 templates present
      git:
        repo: https://git.coop/mc3coop/ssh-templates.git
        dest: /var/www/mc3
        clone: true
        update: true
        force: true
    
    - name: Debian default site disabled
      command: a2dissite 000-default
      register: apache_a2dissite_default
      changed_when: '"already disabled" not in apache_a2dissite_default.stdout'
      when: '"000-default" in apache_sites_loadad'
    
    - name: Debian default /var/www/html/index.html absent
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: WSH Apache config in place
      template:
        src: templates/mc3.conf.j2
        dest: /etc/apache2/conf-available/mc3.conf

  tags:
    - apache
...
