---
- name: mc3 templates present
  git:
    repo: https://git.coop/mc3coop/ssh-templates.git
    dest: /var/www/mc3
    update: true
    force: true
  tags:
    - apache

- name: Check if /etc/apache2/sites-available/000-default exists
  stat:
    path: /etc/apache2/sites-available/000-default
  register: apache_default
  tags:
    - apache

- name: Debian default site disabled
  command: a2dissite 000-default
  register: apache_a2dissite_default
  changed_when: '"already disabled" not in apache_a2dissite_default.stdout'
  when: apache_default is defined and apache_default.stat.exists
  tags:
    - apache

- name: Debian default /var/www/html/index.html absent
  file:
    path: /var/www/html/index.html
    state: absent
  tags:
    - apache

- name: WSH Apache config in place
  template:
    src: templates/mc3.conf.j2
    dest: /etc/apache2/conf-available/mc3.conf
  tags:
    - apache
...
