---
- name: Install mod_md from https://github.com/icing/mod_md
  block:

    - name: Requirements present
      apt:
        pkg:
          - apache2-dev
        state: present

    - name: Find the latest version of mod_md
      block:

        - name: Use a HEAD request to get the latest redirect URL
          uri:
            url: https://github.com/icing/mod_md/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: apache_md_latest_headers

        - name: Set a fact for the latest version of Apache mod_md
          set_fact:
            apache_mod_md_version: "{{ apache_md_latest_headers.location | urlsplit('path') | basename }}"

      when: apache_mod_md_version == "latest"

    - name: Source code present
      git:
        repo: https://github.com/icing/mod_md.git
        dest: /usr/local/src/mod_md
        version: "{{ apache_mod_md_version }}"
        depth: 1
        force: true
        update: true

    - name: Buildconf mod_md
      command: ./buildconf
      args:
        chdir: /usr/local/src/mod_md

    - name: Configure mod_md
      command: ./configure --with-apxs=/usr/bin/apxs --enable-werror
      args:
        chdir: /usr/local/src/mod_md

    - name: Make install mod_md
      make:
        chdir: /usr/local/src/mod_md
        target: install

  tags:
    - apache
...
