# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install mod_md from https://github.com/icing/mod_md
  block:

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - apache2-dev
          - apache2-ssl-dev
          - libcurl4-openssl-dev
          - libjansson-dev
        state: present

    - name: Find the latest version of mod_md
      block:

        - name: Use a HEAD request to get the latest redirect URL
          ansible.builtin.uri:
            url: https://github.com/icing/mod_md/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: apache_md_latest_headers

        - name: Set a fact for the latest version of Apache mod_md
          ansible.builtin.set_fact:
            apache_md_version: "{{ apache_md_latest_headers.location | urlsplit('path') | basename }}"

      when: apache_md_version == "latest"

    - name: Source code present
      ansible.builtin.git:
        repo: https://github.com/icing/mod_md.git
        dest: /usr/local/src/mod_md
        version: "{{ apache_md_version }}"
        depth: 1
        force: true
        update: true
      register: apache_md_repo

    - name: Build and install mod_md
      block:

        - name: Buildconf mod_md
          ansible.builtin.command: ./buildconf
          args:
            chdir: /usr/local/src/mod_md

        - name: Configure mod_md
          ansible.builtin.command: ./configure --with-apxs=/usr/bin/apxs --enable-werror
          args:
            chdir: /usr/local/src/mod_md

        - name: Make install mod_md
          community.general.make:
            chdir: /usr/local/src/mod_md
            target: install

      when: apache_md_repo.changed

  when: apache_md_version != "default"
  tags:
    - apache
...
