# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Apache Ansible role.
#
# The Webarchitects Apache Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Apache Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Apache Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apache mod_md tasks
  block:

    - name: Include mod_md install tasks
      ansible.builtin.include_tasks: md_install.yml
      when:
        - apache_md_version is defined
        - apache_md_version != "default"
      tags:
        - apache_install

    - name: Debug ansible_facts.packages.keys()
      ansible.builtin.debug:
        var: ansible_facts.packages.keys()
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}2{% else %}3{% endif %}"

    - name: Debug Apache mod_md cert copy test
      ansible.builtin.debug:
        msg:
          - "apache_md_cert_cp.pkgs: {{ apache_md_cert_cp.pkgs }}"
          - "ansible_facts.packages.keys(): {{ ansible_facts.packages.keys() }}"
          - "apache_md_cert_cp.pkgs | ansible.builtin.difference(ansible_facts.packages.keys()): {{ apache_md_cert_cp.pkgs | ansible.builtin.difference(ansible_facts.packages.keys()) }}"
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"
      loop: "{{ apache_md_cert_copy }}"
      loop_control:
        loop_var: apache_md_cert_cp
        label: "{{ apache_md_cert_cp.name }}"

    - name: Include Apache mod_md cert copy tasks
      ansible.builtin.include_tasks: md_cert_cp.yml
      loop: "{{ apache_md_cert_copy }}"
      loop_control:
        loop_var: apache_md_cert_cp
        label: "{{ apache_md_cert_cp.name }}"
      when:
        - apache_md_cert_copy is defined
        - apache_md_cert_copy != []
        - apache_md_cert_cp.pkgs | ansible.builtin.difference(ansible_facts.packages.keys()) == []

    - name: Apache reload script in place
      ansible.builtin.template:
        src: apache_md_cert_reload.sh.j2
        dest: /usr/local/bin/apache_md_cert_reload.sh
        owner: root
        group: root
        mode: "0750"

    - name: Crontab for Apache reload script in place
      ansible.builtin.cron:
        name: "Apache mod_md certificate reload"
        special_time: daily
        job: /usr/local/bin/apache_md_cert_reload.sh

  when: apache_md_version != "default"
  tags:
    - apache
...
