---
- name: Check the status of a mod_md cert
  block:

    - name: "Query the status for {{ apache_mdomain }}"
      uri:
        url: "http://localhost/md-status/{{ apache_mdomain }}"
        return_content: true
        status_code:
          - 200
          - 404
      check_mode: false
      register: apache_mdomain_status

    - name: "Debug the mdomain status for {{ apache_mdomain }}"
      debug:
        var: apache_mdomain_status.json
        verbosity: 2
      when: apache_mdomain_status.json is defined

    - name: Set apache_md_certs_present to an empty array
      set_fact:
        apache_md_certs_present: []

    - name: "Set a fact for the mdomain RSA status for {{ apache_mdomain_status }}"
      set_fact:
        apache_md_certs_present: "{{ apache_md_certs_present }} + [ 'rsa3072' ]"
      when:
        - ( apache_md_private_keys is defined )
        - ( "rsa3072" in apache_md_private_keys )
        - ( apache_mdomain_status.status != 404 )
        - ( apache_mdomain_status.json.name is defined )
        - ( apache_mdomain_status.json.name | regex_replace('^"') | regex_replace('"$') ) == apache_mdomain
        - ( apache_mdomain_status.json.cert is defined )
        - ( apache_mdomain_status.json.cert.rsa.ocsp.renewal.last.status is defined )
        - ( apache_mdomain_status.json.cert.rsa.ocsp.renewal.last.status == 0 )

    - name: "Set a fact for the mdomain EC status for {{ apache_mdomain_status }}"
      set_fact:
        apache_md_certs_present: "{{ apache_md_certs_present }} + [ 'secp384r1' ]"
      when:
        - ( apache_md_private_keys is defined )
        - ( "secp384r1" in apache_md_private_keys )
        - ( apache_mdomain_status.status != 404 )
        - ( apache_mdomain_status.json.name is defined )
        - ( apache_mdomain_status.json.name | regex_replace('^"') | regex_replace('"$') ) == apache_mdomain
        - ( apache_mdomain_status.json.cert is defined )
        - ( apache_mdomain_status.json.cert.secp384r1.ocsp.renewal.last.status is defined )
        - ( apache_mdomain_status.json.cert.secp384r1.ocsp.renewal.last.status == 0 )

    - name: Debug apache_md_certs_present array
      debug:
        var: apache_md_certs_present
        verbosity: 2

    - name: Set a fact to indicate the key and cert status is good
        set_fact:
          apache_md_certs: true
      when: apache_md_private_keys | difference(apache_md_certs_present ) | length == 0

    - name: Set a fact to indicate the key and cert status is bad
        set_fact:
          apache_md_certs: false
      when: apache_md_private_keys | difference(apache_md_certs_present ) | length == 0

  tags:
    - apache
...
