---
- name: Switch from mpm_prefork to mpm_event
  block:

    - name: "Disable Apache module {{ apache_phpfpm_mod }}"
      apache2_module:
        name: "{{ apache_phpfpm_mod }}"
        state: absent
      when:
        - apache_phpfpm_mod is defined
        - apache_phpfpm_mod in apache_modules_loaded

    - name: "Disable Apache module mpm_prefork"
      apache2_module:
        name: mpm_prefork
        state: absent
        ignore_configcheck: true

    - name: "Enable Apache mpm_event"
      apache2_module:
        name: mpm_event
        state: present
        ignore_configcheck: true

  when: ( apache_mpm_loaded == "mpm_prefork" ) and ( "mpm_event" in apache_mods_enabled )
  tags:
    - apache

- name: Switch from mpm_event to mpm_prefork
  block:

    - name: "Disable Apache module mpm_event"
      apache2_module:
        name: mpm_event
        state: absent
        ignore_configcheck: true

    - name: "Enable Apache mpm_prefork"
      apache2_module:
        name: mpm_prefork
        state: present
        ignore_configcheck: true

  when: ( apache_mpm_loaded == "mpm_event" ) and ( "mpm_prefork" in apache_mods_enabled )
  tags:
    - apache

- name: Re-check modules enabled
  block:

    - name: Check loaded modules
      block:

        - name: Register the loaded modules
          command: a2query -m
          check_mode: false
          changed_when: false
          register: apache_modules_check

      rescue:

        - name: No mod enabled
          set_fact:
            apache_modules_loaded: []
          when: '"No module matches" in apache_modules_check.stderr'

    - name: Debug the loaded modules
      debug:
        var: apache_modules_check.stdout_lines
        verbosity: 2
      when: apache_modules_check.stdout is defined

    - name: Set an array of the loaded modules
      set_fact:
        apache_modules_loaded: "{{ apache_modules_loaded | default([]) + [ line.split(' ')[0] ] }}"
      when: apache_modules_check.stdout is defined
      loop: "{{ apache_modules_check.stdout_lines }}"
      loop_control:
        loop_var: line
        label: "{{ line }}"

    - name: Debug loaded modules
      debug:
        var: apache_modules_loaded
        verbosity: 2
      when: apache_modules_loaded is defined

  tags:
    - apache
...
