---
- name: Webarchitects templates present
  git:
    repo: https://git.coop/webarch/website-templates.git
    dest: /var/www/wsh
    update: yes
  tags:
    - apache

- name: Debian default site disabled
  command: a2dissite 000-default
  tags:
    - apache

- name: WSH Apache config in place
  template:
    src: templates/webarch.conf.j2
    dest: /etc/apache2/conf-available/webarch.conf
  tags:
    - apache
