---
- name: Config for webarch.coop
  block:

    - name: Webarchitects templates present
      git:
        repo: https://git.coop/webarch/website-templates.git
        dest: /var/www/wsh
        version: master
        clone: true
        update: true
        force: true

    - name: Debian default /var/www/html/index.html absent
      file:
        path: /var/www/html/index.html
        state: absent

    - name: WSH Apache config in place
      template:
        src: templates/webarch.conf.j2
        dest: /etc/apache2/conf-available/webarch.conf

  tags:
    - apache
...
